services:
  app:
    image: zyerin/iplan1
    ports:
      - "8083:8080"
    environment:
      - FIREBASE_CONFIG_PATH=/app/iplan-firebase.json

  app2:
    image: hanna406/iplan-demo
    ports:
      - "8080:8080"
    environment:
      - FIREBASE_CONFIG_PATH=/app/iplan-firebase.json

  app3:
    image: hanni/test1
    ports:
      - "8082:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./src/main/resources/iplan-3e9c2-feef2236cd5b.json
    volumes:
      - ./src/main/resources/iplan-firebase.json:/app/iplan-firebase.json