services:
  redis:
    image: redis
    container_name: rediscont
    networks:
      - myboot
    ports:
      - "6379:6379"
    restart: always

  iplan-server:
    image: hanna406/iplan-demo
    container_name: iplancont
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/iplan-google.json
      - FIREBASE_CONFIG_PATH=/app/iplan-firebase.json
    networks:
      - myboot

networks:
  myboot:
    driver: bridge